### ISSUE TITLE
Security vulnerabilities 

### ISSUE THREAD

**Issue by KateNegrienko** [pip-webui2/pip-webui2-entry#1]
Дорогой Aleksandr Koshevierov @Iworb, почти после каждого вашего коммита в репозитрии у Вас возникает уязвимость. Почините ее пожалуйста. Если у вас будут вопросы, вы можете обратиться лично ко мне или к @Dvoikin. Думаю, Леша с удовольствием вам поможет.
![image](https://user-images.githubusercontent.com/13833386/60888891-682f4800-a260-11e9-92f6-d7ae934f4c48.png)

**Comment by Iworb** [comment]
@KateNegrienko некоторое время не заходил на гитхаб, поэтому увидел только сейчас ваш запрос. Обновил зависимости и на данный момент уязвимостей быть не должно, проверьте так ли это с вашей стороны.
